default:
  deploy:
    parameters:
      stack_name: durable-functions-example
      resolve_s3: true
      s3_prefix: durable-functions-example
      region: us-east-1
      capabilities: CAPABILITY_IAM
      image_repositories: []
  global:
    parameters:
      region: us-east-1
version: 0.1
