default:
  deploy:
    parameters:
      stack_name: album-registration-system
      resolve_s3: true
      s3_prefix: album-registration-system
      region: us-east-2
      capabilities: CAPABILITY_IAM
      image_repositories: []
  global:
    parameters:
      region: us-east-2
version: 0.1
