default:
  deploy:
    parameters:
      stack_name: durable-function-example
      resolve_s3: true
      s3_prefix: durable-function-example
      region: us-east-2
      capabilities: CAPABILITY_IAM
      image_repositories: []
  global:
    parameters:
      region: us-east-2
version: 0.1
